version: "3.2"
services:
  data_science:
    build: .
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    environment:
      - PYTHONPATH=./src
  notebook:
    image: futbolean_data_science:latest
    volumes:
      - ./:/app
    ports:
      - "8888:8888"
    depends_on:
      - data_science
    command: kedro jupyter notebook --ip 0.0.0.0 --no-browser --allow-root
